### ISSUE TITLE
Issues from Forum versions as reported on Forum

### ISSUE THREAD

**Issue by Bunkspucket** [RkShaRkz/Starsector-IntelliJ-Template#10]
Vayra's Sector issue:

 'Anyone seeing this do not use this with AOTD it will crash your game cycle 207 an onward due Vayra's factions unable to parse aotd's industries. Disabling popular front or the factions in the config will not stop this by itself. You must also  go into mods\Vayra's Sector\data\config\vayraColonies.csv and set all to FALSE' reported  [here](https://fractalsoftworks.com/forum/index.php?topic=16058.msg436862#msg436862)

VS Factions don't spawn in after SS updated to .96, ongoing issue summarised in [this post](https://fractalsoftworks.com/forum/index.php?topic=16058.msg399954#msg399954)

Previous Custodian 'TheDrgn' pushed a .96 version of this mod, link on forum page [here](https://fractalsoftworks.com/forum/index.php?topic=16058.msg378227#msg378227)

Kadur Remnant issue:
.
Mod conflict with IndEvo 3.3.d or greater requires custom .jar linked in thread to fix  posted by user 'TheProtagonists' [here](https://fractalsoftworks.com/forum/index.php?topic=6649.msg419431#msg419431)

Previous custodian 'Timid' pushed a .95 verions of this mod, link on [this post](https://fractalsoftworks.com/forum/index.php?topic=6649.msg390365#msg390365)

Vayra's Ship Pack
Previous custodian 'Pet_Mudstone' pushed a  .96 version of this mod, link on forum page [here](https://fractalsoftworks.com/forum/index.php?topic=16059.msg413343#msg413343 )

**Comment by RkShaRkz** [comment]
These could have been separated as different issue each.
Also, I don't really see a particular issue outlined here other then "oh we have had issue reports on forums so lemme dump them on you". 

Please, let's deal with actual issues as they happen, and they will be taken care of accordingly.

**Comment by PreConceptor** [comment]
I have no crash on sector generation with IndEvo and AOTD, so the issue fixed by the custom jar is probably not an issue anymore.

**Comment by Bunkspucket** [comment]
My apologies for the consolidated post, I didn't want to spam your Issues tab with multiple entries for things that may or may not be present - just wished to make you aware of issues that have/had existed with the modset in their iterations after Vayra's own updates.

**Comment by RkShaRkz** [comment]
> My apologies for the consolidated post, I didn't want to spam your Issues tab with multiple entries for things that may or may not be present - just wished to make you aware of issues that have/had existed with the modset in their iterations after Vayra's own updates.

It's alright my man, but you could have at least verified if they're still issues before dumping them in a "hey, these things were issues over the past few years so they might still be". 

That being said, do feel free to verify which of them are still issues then either report them as new individual issues (preferred) or just make a new reply here stating which of the things from the OP are actual issues.

Jumping the gun helps noone.

**Comment by RkShaRkz** [comment]
Closing as non-issue, waiting for individual issues to resurface
