### ISSUE TITLE
Minor gameplay consistency

### ISSUE THREAD

**Issue by PreConceptor** [RkShaRkz/Starsector-IntelliJ-Template#12]
ver 3.3.6

Issue p1: multiple unshielded VSP ships do not have the Rugged Construction hullmod in line with vanilla standards, as they were last updated before the hullmod existed.

Solution p1: Add "rugged" under the builtInMods section of the .ship file for 
vayra_greyhound
vayra_mining_hound
vayra_razorback
vayra_battlement
vayra_fortress
vayra_motte
vayra_redoubt
vayra_tower

Issue p2: Stormhawk Thunder retains full power ion cannon and less OP than baseline version, making it wholly superior in every way instead of a minor upgrade with cost (also due to last being updated before the vanilla Thunder was tweaked).

Solution p2: change ioncannon to ioncannon_fighter in vayra_thunder_warhawk_fighter.variant & change OP cost from 9 to 11 or 12 in wing_data.csv

**Comment by RkShaRkz** [comment]
vayra_greyhound has a shield though. But you know what, fine, implemented in commit  c9ad379 c04843e
