### ISSUE TITLE
Something nuking all planet conditions and colonies.

### ISSUE THREAD

**Issue by Sp1cerub** [RkShaRkz/Starsector-IntelliJ-Template#16]
No idea what triggers this, but when i entered a system my faction disappeared. The system It was located in was reset to unexplored.
Returning to the system to see what had happened, all planents were still labelled as under faction control, but only had the interaction menu of an unsurveyed planet.
It also removes all conditions from every planet, resulting in all surveys coming back with 'Nothing of interest."
I thought that maybe staying away from the system would be a temporary measure, but it seemed that after about 2 or 3 minutes the nuking happens regardless.

**Comment by nikothedude** [comment]
it triggers MPC's market desync error on satellites, meaning the old market was replaced by a new one and didnt have time to properly unapply conditions

its likely all markets are being replaced

**Comment by RkShaRkz** [comment]
did this happen on a new save started with 3.3.7 or just happened on 3.3.7 on a savegame started before 3.3.5, or some other version?

i saw the modlist. old vayra had some wannabe-crashcode that messes some markets up and makes the whole galaxy hostile to you overtime, and you had mods it interacted with. 

could really use more info, e.g. how much time was sunk in the savegame? did it happen soon after starting or after 10+ cycles?

**Comment by Zeta-Zhang** [comment]
Suffered from part of the issue mentioned - in my case planetary condition of all non-colonized, non-discovered planets are erased (even planets that should have guaranteed a condition or two like gas giants), but not the faction disappearing part.
I began the save using Vayra 3.3.7 from scratch and such issue kicked in since, like, 2 or 3 cycles into the game

**Comment by Bunkspucket** [comment]
Confirming Zeta-Zhang's report -  Explored a system in cycle 210 in Jan with two gas giants, a volcanic world, a cryovolcanic world, and an irradiated world; all of them have zero conditions. My colonised world is still fine however. I'm not using Terraforming Made Easy by Audax either.

Happy to supply save file/modlist/logs of any kind should you need.

Edit: I'm not sure how pertinent this is, but in the system beforehand I learned one of the Kadur blueprint packages.

**Comment by RkShaRkz** [comment]
Hopefully fixed by a660363 - lets close the issue for now, and reopen if/when it happens on the new version.
