### ISSUE TITLE
3.3.8 download will not extract

### ISSUE THREAD

**Issue by OmegaS-G** [RkShaRkz/Starsector-IntelliJ-Template#26]
Gives the same reason of 'unknown method' for 1900+ items when extracted, resulting in most of the files missing.  Example below.

!   C:\Users\dan\Documents\Downloads\DOWNLOAD_ME_Vayra.Merged.3.3.8.zip: Unknown method in Vayra Merged\data\campaign\industries.csv

**Comment by RkShaRkz** [comment]
Please try the following steps:

- update 7zip
- redownload the archive
- try extracting again

I tried downloading the release and extracting it, went without a single problem. So, so far - cant reproduce the issue.

**Comment by RkShaRkz** [comment]
Closing due to lack of feedback, and it was confirmed to be a non-issue.
