### ISSUE TITLE
[Issue] Make LunaSettings to be able to turn off each Dmod's effects individually

### ISSUE THREAD

**Issue by RkShaRkz** [RkShaRkz/Starsector-IntelliJ-Template#61]
### Mod Name:
VayraMerged v3.3.12

### Mod Version:
VayraMerged v3.3.12

### What did you expect to happen?
Only the ship with the D-mod to be affected

### What actually happened?
Apparently, all ships are affected (still need to verify)

### Steps to Reproduce:
Get DamagedOptics D-mod on one ship, verify that it affects only that ship and not all of them

### Screenshots/Logs:
none

### Additional info:
bern from corvus reported this

**Comment by RkShaRkz** [comment]
verified as untrue, shame on you bern for making me waste time on this; but since I used a multimodule ship as the other ship, lemme retest it once again with some simple ship just in case.

**Comment by RkShaRkz** [comment]
bern — Today at 8:30 PM
the toggle would be enough for me, but ill keep testing with and without other mods to ensure its not just a me issue

**Comment by RkShaRkz** [comment]
> Shark — Today at 10:05 PM
alright.
might i trouble you to update the issue i sent you some time ago with "As per our discord discussion we agreed for a LunaSetting to toggle off the functionality of the Distorted Optics dmod"

somehow i guess he won't even bother to send the video but fine, I'll make a lunasetting to toggle this dmod off because whine.gif

**Comment by bernsssss** [comment]
according to our discord discussion, we agreed for a Luna settings toggle for distorted optics functionality. Video has also been sent apologies for delay

**Comment by RkShaRkz** [comment]
no problemo, i'll make you a lunasetting when i can :)

**Comment by RkShaRkz** [comment]
The setting should apply to both player and enemy, but perhaps a two setting approach, one which disables it for just the player and one which disables it for both would be a nice ticket.

**Comment by RkShaRkz** [comment]
Merged-in in commit 82c389

resolving as done.
